### ISSUE TITLE
validate data

### ISSUE THREAD

**Issue by odanoburu** [own-pt/own-en-legacy#38]
### TODO
- [ ] check references
  - [x] targets exist
  - [x] pointers exist
  - [ ] frames exist
  - [ ] no duplicate references

- [ ] `lex_id` indexing is correct
- [ ] sort words and synsets (for stability)

### discussion

- do we want to have the validator also be a normalizer? we'd have to keep comments in the data structure, but that means we wouldn't have to issue warning about sorting, etc.

please add more suggestions.

**Comment by arademaker** [comment]
This is endless topic. We should start with these minimum set of constraints and improve. We also should try to read the grind code.

**Comment by odanoburu** [comment]
```sparql
select ?wordSense1 ?wordSense2
{
  ?wordSense1 wn30:derivationallyRelated ?wordSense2 .
  FILTER NOT EXISTS { ?synset wn30:containsWordSense ?wordSense2 }
}
```

shows word senses that are objects of a `derivationallyRelated` relation, but that are part of no synset (i.e., are not linked to one by a `containsWordSense` relation
